---
version: "3"
services:
  app:
    build: .
    container_name: lumen_scaffold
    command: >-
      sh -c "
        apk add php8-pecl-xdebug && composer install ;\
        cp .docker/xdebug.ini /etc/php8/conf.d/50_xdebug.ini ;\
        php -S 0.0.0.0:80 -t public"
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .docker/xdebug.ini
      - .:/var/www/html:rw
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: lumen_scaffold_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: lumen_scaffold_cache
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
    networks:
      - app_network

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"
