---
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_scaffold
    command: >-
      sh -c "
        apt-get update -y && apt-get install php8.0-xdebug -y && composer install ;\
        cp .docker/xdebug.ini /etc/php/8.0/mods-available/xdebug.ini ;\
        php artisan serve --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .docker/xdebug.ini
      - .:/var/www/html:rw
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: laravel_scaffold_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: laravel_scaffold_cache
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
    networks:
      - app_network

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"
